apiVersion: apps/v1
kind: Deployment
metadata:
  name: rock-paper-scissors-deployment
  labels:
    app: rock-paper-scissors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rock-paper-scissors
  template:
    metadata:
      labels:
        app: rock-paper-scissors
    spec:
      containers:
        - name: rock-paper-scissors
          image: geraldakenji/rock-image:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: FLASK_ENV
              value: "production"
