apiVersion: v1
kind: Service
metadata:
  name: rock-paper-scissors-service
spec:
  selector:
    app: rock-paper-scissors
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # Change to 'NodePort' for local testing
